/* Auto-generated by cbindgen. Do not edit. See mfsk-ffi-ft8/src/lib.rs. */

#ifndef MFSK_FT8_H
#define MFSK_FT8_H

#pragma once

#include <stdint.h>
#include <stddef.h>

/**
 * Outcome of a decode call.
 */
typedef enum MfskFt8Status {
  /**
   * Decode completed (zero or more results in `out`).
   */
  MFSK_FT8_STATUS_OK = 0,
  /**
   * One of the input pointers was null.
   */
  MFSK_FT8_STATUS_NULL_POINTER = -1,
  /**
   * `n_samples` is too short for a 14-second slot at 12 kHz.
   */
  MFSK_FT8_STATUS_AUDIO_TOO_SHORT = -2,
  /**
   * `depth` is outside `0..=2`.
   */
  MFSK_FT8_STATUS_BAD_DEPTH = -3,
  /**
   * Caller-provided basis scratch too small (only meaningful for
   * the `_into` variant). The required minimum is
   * [`mfsk_ft8_basis_scratch_len`].
   */
  MFSK_FT8_STATUS_SCRATCH_TOO_SMALL = -4,
} MfskFt8Status;

/**
 * Mirrors `mfsk_core::ft8::decode::DecodeDepth`. The deeper levels
 * trade decode time for recall on busy bands.
 */
typedef enum MfskFt8Depth {
  /**
   * `Bp(llra)` only — fast nsym=1 LLR + one BP run per candidate.
   */
  MFSK_FT8_DEPTH_BP = 0,
  /**
   * Above + four full LLR variants on candidates that fail Bp.
   */
  MFSK_FT8_DEPTH_BP_ALL = 1,
  /**
   * Above + OSD-1 / OSD-3 fallback (gated on sync-quality ≥ 12).
   */
  MFSK_FT8_DEPTH_BP_ALL_OSD = 2,
} MfskFt8Depth;

/**
 * One decoded FT8 message.
 *
 * `text` is a C string of at most 39 visible UTF-8 characters plus
 * NUL terminator (FT8's 77-bit message decompresses to ≤ ~36 chars
 * in practice — the buffer is sized at 40 for safety).
 */
typedef struct MfskFt8Result {
  /**
   * NUL-terminated UTF-8 unpacked message. ASCII in practice.
   */
  char text[40];
  /**
   * Carrier frequency of the decoded slot, Hz.
   */
  float freq_hz;
  /**
   * Time offset relative to the slot start, seconds.
   */
  float dt_sec;
  /**
   * SNR estimate (dB, WSJT-X 2500 Hz reference). On the embedded
   * path this reads ~4–12 dB low on strong signals — see
   * `docs/EMBEDDED.md` "Known limitations".
   */
  float snr_db;
  /**
   * Number of bits the LDPC decoder corrected before CRC pass.
   */
  uint32_t hard_errors;
  /**
   * Stage that produced the decode (0 = fast Bp, 1 = full Bp, …).
   */
  uint8_t pass;
  /**
   * Padding to keep the struct C-friendly across compilers.
   */
  uint8_t _pad[3];
} MfskFt8Result;

/**
 * Result list — owned by the FFI side. Free with
 * [`mfsk_ft8_result_list_free`].
 */
typedef struct MfskFt8ResultList {
  /**
   * Pointer to the first result, or null if `len == 0`.
   */
  struct MfskFt8Result *items;
  /**
   * Number of valid entries.
   */
  uintptr_t len;
  /**
   * Capacity (private — only the free function reads this).
   */
  uintptr_t _capacity;
} MfskFt8ResultList;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Required scratch length (in i16 elements) for the `_into` variant.
 * Caller must allocate two arrays of at least this length, both in
 * internal RAM (not PSRAM) for the dot-product kernel to perform.
 */
 uintptr_t mfsk_ft8_basis_scratch_len(void);

/**
 * **Primary FT8 decode** — caller provides BASIS scratch (two i16
 * arrays of [`mfsk_ft8_basis_scratch_len`] elements each, in
 * internal RAM, NOT PSRAM). Avoids per-decode allocation of the
 * 60 KB basis. Required for peak throughput on PSRAM-equipped
 * targets like ESP32 Core2 — the dot-product kernel needs the
 * basis in fast internal RAM. **Use this in production embedded
 * code.**
 *
 * `freq_min_hz` / `freq_max_hz` bound the carrier search range
 * (typical: 200, 3000). `sync_min` is the stage-2 candidate
 * threshold (typical 1.0). `max_cand` caps the survivors after
 * Pass 2 (typical 30 for embedded busy-band). `depth` picks the
 * decoder staircase (`MFSK_FT8_DEPTH_BP_ALL_OSD` = 2 is the most
 * thorough).
 *
 * Only available under the `embedded-fixed-point` feature (the
 * scratch-bearing path lives in mfsk-core's `cfg(fixed-point)`
 * block). Host code should use [`mfsk_ft8_decode_i16_alloc`].
 *
 * # Safety
 * `audio` must point to `n_samples` valid `i16` values; at least
 * 168 000 (14 s × 12 kHz). `basis_re` and `basis_im` must each
 * point to at least `mfsk_ft8_basis_scratch_len()` valid i16
 * elements writable for the duration of the call. `out` must point
 * to a writable [`MfskFt8ResultList`]. Single-threaded — one decode
 * at a time per process.
 */

enum MfskFt8Status mfsk_ft8_decode_i16(const int16_t *audio,
                                       uintptr_t n_samples,
                                       float freq_min_hz,
                                       float freq_max_hz,
                                       float sync_min,
                                       int max_cand,
                                       enum MfskFt8Depth depth,
                                       int16_t *basis_re,
                                       int16_t *basis_im,
                                       struct MfskFt8ResultList *out);

/**
 * **Host-only heap-alloc convenience** — same shape as
 * [`mfsk_ft8_decode_i16`] but allocates the BASIS scratch
 * internally on every call (~60 KB × 2 = ~120 KB heap traffic per
 * decode).
 *
 * Only available on host (`feature = "host"`). Deliberately
 * excluded from embedded builds: surprise per-call heap-allocation
 * of a 60 KB scratch is a bad default for an MCU, and on Core2 with
 * PSRAM the scratch lands in slow PSRAM and tanks the dot-product
 * inner kernel. Embedded callers must use [`mfsk_ft8_decode_i16`]
 * with caller-managed scratch in internal RAM.
 *
 * # Safety
 * Same as [`mfsk_ft8_decode_i16`] minus the scratch arguments.
 */

enum MfskFt8Status mfsk_ft8_decode_i16_alloc(const int16_t *audio,
                                             uintptr_t n_samples,
                                             float freq_min_hz,
                                             float freq_max_hz,
                                             float sync_min,
                                             int max_cand,
                                             enum MfskFt8Depth depth,
                                             struct MfskFt8ResultList *out);

/**
 * Free a result list previously populated by
 * `mfsk_ft8_decode_i16` / `mfsk_ft8_decode_i16_into`. Safe to call
 * with a zero-length list. After this returns, the list's `items`
 * pointer is invalid; the struct itself remains valid for reuse.
 *
 * # Safety
 * `list` must be either null (no-op) or point to a `MfskFt8ResultList`
 * previously populated by this crate.
 */
 void mfsk_ft8_result_list_free(struct MfskFt8ResultList *list);

/**
 * Required output length (in samples) for the synth functions.
 * Equals `NN × 1920 = 151 680` (12.64 s of 12 kHz mono).
 */
 uintptr_t mfsk_ft8_synth_output_len(void);

/**
 * Pack a standard 77-bit FT8 message from three tokens — the
 * typical CQ shape `mfsk_ft8_pack77("CQ", "JA1ABC", "PM86")`. For
 * reply / report messages: `mfsk_ft8_pack77("JA1ABC", "W1AW",
 * "-12")`. Strings must be NUL-terminated UTF-8 (ASCII in
 * practice).
 *
 * Writes 77 bytes (each 0 or 1) to `out_message77`. Returns
 * `MfskFt8Status::Ok` on success, `BadDepth` is reused as a
 * generic "bad input" indicator if any string fails to pack
 * (callsign too long, bad characters, etc).
 *
 * # Safety
 * `call1`, `call2`, `report` must point to valid NUL-terminated
 * C strings. `out_message77` must point to a writable 77-byte
 * buffer.
 */

enum MfskFt8Status mfsk_ft8_pack77(const char *call1,
                                   const char *call2,
                                   const char *report,
                                   uint8_t *out_message77);

/**
 * Convert a 77-bit FT8 message into the 79-tone Gray-mapped
 * sequence. Wraps `mfsk_core::ft8::wave_gen::message_to_tones`.
 * LDPC encode + CRC-14 + Costas insertion all happen inside.
 *
 * `message77` must point to 77 valid bytes (each 0 or 1).
 * `out_itone` receives 79 bytes (each 0..7).
 *
 * # Safety
 * Both pointers must be non-null and writable for their lengths.
 */
 enum MfskFt8Status mfsk_ft8_message_to_tones(const uint8_t *message77, uint8_t *out_itone);

/**
 * Synthesise FT8 i16 PCM (12 kHz mono) from a 79-tone sequence
 * into a caller-provided buffer. `out` must be at least
 * [`mfsk_ft8_synth_output_len`] = 151 680 samples; longer is fine
 * (only the prefix is written). `f0_hz` is the carrier frequency
 * (typical 1500 Hz). `amplitude_i16` peaks at the given value
 * (typical 16 384 ≈ i16_max / 2 for ~50 % full scale headroom).
 *
 * Output covers 12.64 s of audio (79 symbols × 1920 samples /
 * 12 kHz). Caller is responsible for slot-aligning this within an
 * FT8 14-second window if transmitting (typical: prepend 0.5 s of
 * silence + append 0.86 s of trailing silence to match the
 * receive-side `TX_START_OFFSET_S`).
 *
 * # Safety
 * `itone` must point to 79 valid bytes (each 0..7). `out` must
 * point to a writable buffer of at least `out_len` i16 samples.
 * Returns `ScratchTooSmall` if `out_len < TONES_OUTPUT_LEN`.
 */

enum MfskFt8Status mfsk_ft8_tones_to_i16(const uint8_t *itone,
                                         float f0_hz,
                                         int16_t amplitude_i16,
                                         int16_t *out,
                                         uintptr_t out_len);

/**
 * f32 variant of [`mfsk_ft8_tones_to_i16`]. `amplitude` is unitless
 * (typical 0.5 for ~−6 dBFS). Same buffer-length rules.
 *
 * # Safety
 * Same as [`mfsk_ft8_tones_to_i16`] — `itone` must point to 79
 * valid bytes, `out` must point to a writable f32 buffer of at
 * least `out_len` samples; returns `ScratchTooSmall` if `out_len`
 * is below `mfsk_ft8_synth_output_len()`.
 */

enum MfskFt8Status mfsk_ft8_tones_to_f32(const uint8_t *itone,
                                         float f0_hz,
                                         float amplitude,
                                         float *out,
                                         uintptr_t out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MFSK_FT8_H */
